### ISSUE TITLE
heyo

### ISSUE THREAD

**Issue by mrousavy** [marcelo-msbg/VIsionCameraDemo#1]
nice blog post!

quick tip; you can now convert the Frame from YUV -> RGB, and resize it using [vision-camera-resize-plugin](https://github.com/mrousavy/vision-camera-resize-plugin) :)

**Comment by marcelo-msbg** [comment]
Thanks!

It really makes things easy. I will take a look and include it in the following parts of the article. 

Great job on the library!

**Comment by mrousavy** [comment]
awesome, thanks! :)
